edges:
  hosts:  { from: machine, to: service, directed: true }
  serves: { from: database, to: recordset, directed: true }
  delivers: { from: database, to: views , directed: true }
  procedures: { from: database, to: storeprocedure, directed: true }
  indexes: { from: database, to: index, directed: true }
  gets:  { from: api, to: task, colour: "#4a9eff", directed: true }
  selects:  { from: recordset, to: task, colour: "#4a9eff", directed: true }
  funcs:  { from: recordset, to: storedprocedure, colour: "#4a9eff", directed: true }
  procs:  { from: storedprocedure, to: recordset, colour: "#4a9eff", directed: true }
  views: { from: recordset, to: view, colour: "#4a9eff", directed: true }
  upserts: { from: task, to: recordset, colour: "#e94560", directed: true }
  calls: { from: task, to: storedprocedure, colour: "#e94560", directed: true }
  writes: { from: task, to: file, colour: "magenta", directed: true }
  indexes: { from: task, to: index, colour: "#e94560", directed: true }
  sends: { from: task, to: service, colour: "#dd1111", directed: true }
  posts: { from: task, to: api, colour: "#e94560", directed: true }
nodes:
  machine:  { shape: box }
  service:  { shape: hexagon }
  recordset:    { shape: cylinder }
  storedprocedure:    { shape: cylinder }
  task:     { shape: diamond }
  database: {shape: cylinder }
  index: {shape: ellipse}
  api: {shape: cloud}
  dll: {shape: triangle}
  file: { shape: square }
  view:  { shape: cylinder }