schema: infra

X3CustomerPull:
  kind: task
  cadence: 10mins
  reads: [x3-api-customer, exportmaster]
  writes: [x3rocs-customer, x3rocs-contact, x3rocs-pricediscount]

EMUpdater:
  kind: task
  cadence: 10mins
  reads: [x3.customers_needing_em_update]
  writes: [exportmaster-dll]

RIVSEM01:
  kind: machine
  hosts: [Expormaster, Exportmaster-dll]

X3ROCS:
  kind: database
  service: [PostgreSQL]


PostgreSQL:
  kind: service

x3.customers_needing_em_update:
  kind: view
  reads: [x3.customer]

x3.customer:
  kind: table
  database: [X3ROCS]

RIVSPROD01:
  kind: machine
  hosts: [X3ROCS]  

exportmaster: 
  kind: service
  
exportmaster-dll:
  kind: service

x3rocs-customer:
  kind: table
  
