schema: infra

X3CustomerPull:
  kind: task
  cadence: 10mins
  selects: [x3api.customer, x3db.bpcustomer, exportmaster.customer]
  upserts: [x3rocs.customer, x3rocs.contact, x3rocs.pricediscount]
  writes: [logs.x3customerpull]

x3api.customer:
  kind: api

x3api.invoice:
  kind: api

x3db:
  kind: database
  serves: [x3db.bpcustomer]

x3db.bpcustomer:
  kind: recordset

x3db.bpcinvlig:
  kind: recordset

x3db.sinvoice:
  kind: recordset

x3db.gacentry:
  kind: recordset

x3rocs:
  kind: database
  service: PostgreSQL
  serves: [x3rocs.customer, x3rocs.contact, x3rocs.pricediscount, x3rocs.invoice-header, x3rocs.uploaded-invoices, x3rocs.invoice-line, x3rocs.invoice-attempt, x3rocs.customers-needing-em-update ]

x3rocs.customer:
  kind: recordset

x3rocs.contact:
  kind: recordset

x3rocs.invoice-header:
  kind: recordset

x3rocs.invoice-line:
  kind: recordset

x3rocs.pricediscount:
  kind: recordset

x3rocs.service-errors:
  kind: recordset

x3rocs.uploaded-invoices:
  kind: recordset

x3rocs.customers-needing-em-update:
  kind: storedprocedure
  selects: [x3rocs.customer]

x3rocs.update-contact-keycloak-hash:
  kind: storedprocedure  

exportmaster:
  kind: database
  service: Exportmaster
  serves: [exportmaster.customer, exportmaster.analysis, exportmaster.orderh, exportmaster.orderi, exportmaster.quoteh]

exportmaster.customer:
  kind: recordset

EMUpdater:
  kind: task
  cadence: 10mins
  selects: [x3rocs.customers-needing-em-update]
  writes: [logs.emupdater]
  sends: [exportmaster-dll]

RIVSEM01:
  kind: machine
  hosts: [Exportmaster, exportmaster-dll]

PostgreSQL:
  kind: service

RIVSPROD01:
  kind: machine
  hosts: [x3rocs, smtp, PostgreSQL]  

exportmaster-dll:
  kind: service

smtp:
  kind: service

InvoiceExtractor:
  kind: task
  selects: [exportmaster.analysis, exportmaster.orderh, exportmaster.orderi, exportmaster.quoteh, x3rocs.customer, x3rocs.invoice-header, x3rocs.uploaded-invoices]
  upserts: [x3rocs.invoice-header, x3rocs.invoice-line, x3rocs.invoice-attempt ]
  writes: [logs.invoiceextractor]

InvoiceUploader:
  kind: task
  posts: [x3api.invoice]
  selects: [x3rocs.customer, x3rocs.invoice-header, x3rocs.invoice-attempt, x3rocs.uploaded-invoices, x3db.bpcinvlig, x3db.sinvoice, x3db.gacentry]
  upserts: [x3rocs.invoice-attempt, x3rocs.invoice-line, x3rocs.uploaded-invoices, x3rocs.invoice-header]
  writes: [logs.invoiceuploader]

KeycloakUpdater:
  kind: task
  selects: [kc.rocs-heartbeats, kc.user-entity, kc.user-attribute, kc.credential, kc.keycloak-role, kc.client, x3rocs.contact]
  upserts: [kc.rocs-heartbeats, kc.user-entity, kc.user-attribute, kc.credential, kc.user-role-mapping, x3rocs.contact, x3rocs.update-contact-keycloak-hash, x3rocs.service-errors]
  writes: [logs.keycloakupdater]
  sends: [smtp]

Keycloak:
  kind: database
  serves: [kc.rocs-heartbeats, kc.user-entity, kc.user-attribute, kc.credential, kc.keycloak-role, kc.client, kc.user-role-mapping]

kc.rocs-heartbeats:
    kind: recordset
    
kc.user-entity:
    kind: recordset

kc.user-attribute:
    kind: recordset

kc.credential:
    kind: recordset

kc.keycloak-role:
    kind: recordset

kc.client:
    kind: recordset

kc.user-role-mapping:
    kind: recordset

logs.keycloakupdater:
  kind: file

logs.x3customerpull:
  kind: file

logs.invoiceuploader:
  kind: file

logs.invoiceextractor:
  kind: file

logs.emupdater:
  kind: file

exportmaster.quoteh:
  kind: recordset

exportmaster.orderh:
  kind: recordset

exportmaster.orderi:
  kind: recordset

exportmaster.analysis:
  kind: recordset




