schema: infra

X3CustomerPull:
  kind: task
  cadence: 10mins
  selects: [x3api.customer, x3db.bpcustomer, exportmaster.customer]
  upserts: [x3rocs.customer, x3rocs.contact, x3rocs.pricediscount]
  writes: [logs.x3customerpull]

x3api.customer:
  kind: api

x3db:
  kind: database
  serves: [x3db.bpcustomer]

x3db.bpcustomer:
  kind: recordset

x3db.bpcinvlig:
  kind: recordset

x3db.sinvoice:
  kind: recordset

x3db.gacentry:
  kind: recordset

x3rocs:
  kind: database
  service: PostgreSQL
  serves: [x3rocs.customer, x3rocs.contact, x3rocs.pricediscount,x3rocs.invoice_header, x3rocs.uploaded_invoices, x3rocs.invoice_line, x3rocs.invoice_attempt, x3rocs.customers_needing_em_update ]

x3rocs.customer:
  kind: recordset
  
x3rocs.customers_needing_em_update:
  kind: recordset
  selects: [x3rocs.customer]

exportmaster:
  kind: database
  service: Exportmaster
  serves: [exportmaster.customer, exportmaster.analysis, exportmaster.orderh, exportmaster.orderi, exportmaster.quoteh]

exportmaster.customer:
  kind: recordset

EMUpdater:
  kind: task
  cadence: 10mins
  selects: [x3rocs.customers_needing_em_update]
  writes: [logs.emupdater]
  sends: [exportmaster-dll]

RIVSEM01:
  kind: machine
  hosts: [Exportmaster, exportmaster-dll]

PostgreSQL:
  kind: service

RIVSPROD01:
  kind: machine
  hosts: [x3rocs, smtp, PostgreSQL]  

exportmaster-dll:
  kind: service

smtp:
  kind: service

InvoiceExtractor:
  kind: task
  selects: [exportmaster.analysis, exportmaster.orderh, exportmaster.orderi, exportmaster.quoteh, x3rocs.customer, x3rocs.invoice_header, x3rocs.uploaded_invoices]
  upserts: [x3rocs.invoice_header, x3rocs.invoice_line, x3rocs.invoice_attempt ]
  writes: [logs.invoiceextractor]

InvoiceUploader:
  kind: task
  posts: [x3api.invoice]
  selects: [x3rocs.customer, x3rocs.invoice_header, x3rocs.invoice_attempt, x3roc3.uploaded_invoices, x3db.bpcinvlig, x3db.sinvoice, x3db.gacentry]
  upserts: [x3rocs.invoice_attempt, x3rocs.invoice_line, x3roc3.uploaded_invoices, x3rocs.invoice_header]
  writes: [logs.invoiceuploader]

KeycloakUpdater:
  kind: task
  selects: [kc.rocs-heartbeats, kc.user-entity, kc.user-attribute, kc.credential, kc.keycloak-role, kc.client, x3rocs.contact]
  upserts: [kc.rocs-heartbeats, kc.user-entity, kc.user-attribute, kc.credential, kc.user-role-mapping, x3rocs.contact, x3.update_contact_keycloak_hash, x3rocs.service-errors]
  writes: [logs.keycloakupdater]
  sends: [smtp]

  